#!/usr/bin/env bash
# Writes STATEMENTS.md, the map from the numbered statements of the paper to the Lean declarations and to the
# scripts and recorded outputs, from paper/main.tex and the numbers of paper/main.aux (build the paper first).
# Next to the \label of each mapped statement, three macros that print nothing:
#   \leanmap{A, B}        its Lean declarations, full names (empty: not formalized)
#   \codemap{S > O, ...}  its scripts S and recorded outputs O, paths from the root of the repository
#   \mapnote{text}        how the formal or computed result differs from the statement
# Checks: every declaration is declared in RegretKappa/ (outside the Comparator challenge and Solution.lean), and every
# path exists. Exits 1 if a check fails. Run from anywhere: paper/statement_map.sh
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f paper/main.aux ] || { echo "no paper/main.aux: build the paper first" >&2; exit 1; }
rc=0
perl - paper/main.tex paper/main.aux > STATEMENTS.md.tmp <<'PERL' || rc=$?
use strict; use warnings;
my ($tex, $aux) = @ARGV;
my %num;
open my $A, '<', $aux or die; while (<$A>) { $num{$1} = $2 if /^\\newlabel\{([^}]*)\}\{\{([^}]*)\}/ } close $A;
open my $T, '<', $tex or die; my $s = do { local $/; <$T> }; close $T;
$s =~ s/(?<!\\)%[^\n]*//g;
sub group { my ($str, $pos) = @_; my $d = 0; my $i = $pos;    # balanced {...} starting at $pos
  for (; $i < length $str; $i++) { my $c = substr($str, $i, 1);
    if ($c eq '\\') { $i++; next } $d++ if $c eq '{'; if ($c eq '}') { $d--; return (substr($str, $pos + 1, $i - $pos - 1), $i + 1) if $d == 0 } }
  die "unbalanced group at $pos\n"; }
my %mac;    # macros without arguments, expanded inside math
while ($s =~ /\\(?:re)?newcommand\{\\([A-Za-z]+)\}\{/g) { my $n = $1; my ($b) = group($s, pos($s) - 1); $mac{$n} = $b }
sub math { my $x = shift;
  for my $n (sort { length $b <=> length $a } keys %mac) { $x =~ s/\\\Q$n\E(?![A-Za-z])/$mac{$n}/g }
  $x =~ s/\\\|/\\Vert /g; $x =~ s/\|/\\vert /g; "\$`$x`\$" }
sub md { my $x = shift; $x =~ s/\\lname\{([^}]*)\}/`$1`/g; $x =~ s/\\_/_/g; $x =~ s/\$([^\$]+)\$/math($1)/ge;
  $x =~ s/~/ /g; $x =~ s/\\ref\{([^}]*)\}/$num{$1} \/\/ '??'/ge; $x =~ s/\s+/ /g; $x }
my %kind = (thm => 'Theorem', lem => 'Lemma', prop => 'Proposition', cor => 'Corollary', comp => 'Computation',
  def => 'Definition', rem => 'Remark', q => 'Question', tab => 'Table', sec => 'Section', subsec => 'Section');
# Map macros right after a \label (blanks between) belong to it; the others to the last section label before them.
my (@order, %row, $fail, $lab, $labend, $sec);
while ($s =~ /\\label\{([^}]*)\}|\\(leanmap|codemap|mapnote)(?=\{)/g) {
  if (defined $1) { ($lab, $labend) = ($1, pos($s)); $sec = $lab if $lab =~ /^(sec|subsec):/; next }
  my ($name, $start) = ($2, $-[0]); my ($body, $end) = group($s, pos($s)); pos($s) = $end;
  my $t;
  if (defined $lab && substr($s, $labend, $start - $labend) =~ /^\s*$/) { $t = $lab; $labend = $end } else { $t = $sec }
  defined $t or die "map macro before any label\n";
  my ($k) = $t =~ /^([a-z]+):/; $kind{$k // ''} or die "no kind for label $t\n";
  push @order, $t unless $row{$t};
  $row{$t} //= { lean => [], code => [], note => [] };
  if ($name eq 'leanmap') { push @{ $row{$t}{lean} }, grep { length } map { s/^\s+|\s+$//gr } split /,/, $body }
  elsif ($name eq 'codemap') { push @{ $row{$t}{code} }, grep { length } map { s/^\s+|\s+$//gr } split /,(?![^(]*\))/, $body =~ s/\\_/_/gr }
  else { push @{ $row{$t}{note} }, md($body) }
}
my @rows = map { my ($k) = /^([a-z]+):/; [ "$kind{$k} " . ($num{$_} // die("no number for $_\n")), $row{$_}{lean}, $row{$_}{code}, join(' ', @{ $row{$_}{note} }) ] } @order;
my %decl;
for my $f (split /\n/, `find RegretKappa -name '*.lean' ! -name Challenge.lean ! -path 'RegretKappa/Challenge/*' ! -name Solution.lean | LC_ALL=C sort`) {
  open my $L, '<', $f or die; my @ns;
  while (<$L>) {
    if (/^\s*namespace\s+(\S+)/) { push @ns, $1; next }
    if (/^\s*end\s+(\S+)/ && @ns && $ns[-1] =~ /(^|\.)\Q$1\E$/) { pop @ns; next }
    if (/^\s*(?:@\[[^\]]*\]\s*)?(?:(?:private|protected|noncomputable)\s+)*(?:theorem|lemma|def|abbrev|structure|inductive|instance|class)\s+([^\s:({]+)/) {
      $decl{join('.', @ns, $1)} = 1 }
  }
}
for my $r (@rows) {
  for my $d (@{ $r->[1] }) { next if $decl{$d}; print STDERR "FAIL $r->[0]: no declaration $d in RegretKappa/\n"; $fail = 1 }
  for my $c (@{ $r->[2] }) { for my $p (split / > /, $c) { my ($path) = split ' ', $p;
    next if -e $path; print STDERR "FAIL $r->[0]: no file $path\n"; $fail = 1 } }
}
print "# From the paper to the checks\n\n";
print "Each numbered statement of the paper that a formal proof or a computation bears on: its Lean declarations, its scripts with their recorded outputs (`script > output`), and how the checked result differs from the statement. Generated by `paper/statement_map.sh` from `paper/main.tex`.\n\n";
print "| Statement | Lean | Scripts and recorded outputs | Note |\n| --- | --- | --- | --- |\n";
for my $r (@rows) {
  my $lean = @{ $r->[1] } ? join(', ', map { "`$_`" } @{ $r->[1] }) : ($r->[0] =~ /^(Table|Section) / ? '' : 'not formalized');
  my $code = join('<br>', map { join(' > ', map { my ($p, @rest) = split ' ', $_; "`$p`" . (@rest ? " @rest" : '') } split / > /, $_) } @{ $r->[2] });
  my $note = $r->[3]; $note = '' if $note eq 'not formalized' && !@{ $r->[1] };
  print "| $r->[0] | $lean | $code | $note |\n";
}
exit($fail ? 1 : 0);
PERL
mv STATEMENTS.md.tmp STATEMENTS.md
exit $rc
